### ISSUE TITLE
Validate against related data?

### ISSUE THREAD

**Issue by ericclemmons** [js-data/js-data-schema#11]
Suppose I'm validating the following:

```javascript
{
  email: "foo@example.com",
  reEmail: "foo@example.com",
}
```

I'd like to ensure that my `email` validator can confirm that the user re-entered it correctly to verify.

Does this project support accessing the entire object that's being validated, vs. just the single value?

/cc @willrstern

**Comment by jmdobry** [comment]
In js-data-schema 1.2.0 I added support for this. When you define a custom rule the rule function will be invoked in the context of the object under test.

Here is [a plunker](http://plnkr.co/edit/LV6c0Y?p=preview) that demonstrates.

**Comment by willrstern** [comment]
Awesome, thanks!
