### ISSUE TITLE
Rule names conflict with schema-attribute names

### ISSUE THREAD

**Issue by willrstern** [js-data/js-data-schema#15]
A schema-attribute named `email` will error if there is a rule named `email`
```javascript
schemator.defineRule('email', function (x) {
  return null;
});

var schema = schemator.defineSchema('mySchema', {
  //this schema errors because field "email" matches a rule name
  email: {
    email: true
  }
});
```

This prevents from using on data structures with attributes such as "type", "max", or any custom rule.

It's happening here...
https://github.com/js-data/js-data-schema/blob/master/lib/schema.js#L225

**Comment by jmdobry** [comment]
Yeah, I had been thinking about simply deleting that line of code. And the tests pass without it, so I'll do it shortly.

**Comment by willrstern** [comment]
Oh nice.  I was gonna submit a pr with it out (I noticed the passing tests as well), but wasn't sure why it was in place.

Thanks again!
