### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by willrstern** [js-data/js-data-schema#18]
As sad as IE8 is, it still accounts for over 5% of my company's revenue.

Do you currently know what it would take for IE8 support to js-data-schema?
Were there any pain points that prevented it in the past?

**Comment by jmdobry** [comment]
Off the top of my head, I don't know what it would take. Have you tried it in IE8? What problems did you encounter?

**Comment by willrstern** [comment]
I just ran into it now...I'll see what all it will take.  I wouldn't expect much.

**Comment by willrstern** [comment]
So it's due to the fact that some of my fields have no schema/validation against them.  This works in all browsers, up until IE8.  I'm not sure if you consider that a developer error or library error, but here's a pr showing what it takes to fix it: https://github.com/js-data/js-data-schema/pull/19
