### ISSUE TITLE
List of validator rules

### ISSUE THREAD

**Issue by mikeerickson** [js-data/js-data-schema#20]
Is there a list of built-in validator rules?

- [ ] I am trying to define a column has a required value
- [ ] I am trying to define a column must be true
- [ ] I am trying to define a column which has a least one of a required array item (must have at least one of master hobbies)
- [ ] state must be `CA`
- [ ] married must be `true`

I realize I can create custom rules, but no sense in reinventing wheel if they already exist

```
schemator.defineSchema('Family', {
	fname: {type: 'string', nullable: false},
	lname: {type: 'string', nullable: false},
	email: 'string',
	dob: 'date',
	state: 'string',
	hobbies: 'array',
	gender: 'string',
	married: {type: 'boolean', nullable: false},
	bio: 'string'
});
```

**Comment by jmdobry** [comment]
You can get the list of default rules via `schemator. availableRulesI()`
