### ISSUE TITLE
Custom defined rule is not called on multiple attributes

### ISSUE THREAD

**Issue by gtarcea** [js-data/js-data-schema#9]
When I define  a custom rule as follows and use it in multiple spots, the rule is only called for one attribute. Here is my example:

schema.defineRule('mustExist',  mustExist, true);

schema.defineSchema('Sample', {
   project_id: {
       type: 'string',
       minLength: 1,
       mustExist: 'projects'
   },
   owner: {
       type: 'string',
       minLength: 1,
       mustExist: 'users'
   }
}

In this case the mustExist rule will look up the item in the named table to validate it exists. However, when I run schema.validate, the only rule defined for mustExist, has the value 'users' associated with it. Only one instance of the rule and its arguments are being kept.

I have a pull request I'll be submitting that resolves this issue.

**Comment by jmdobry** [comment]
Do you experience this issue when you use `validateSync`? Or only with `validate`?

**Comment by gtarcea** [comment]
It happens with validate. I ran into an issue with validateSync in that 
my async rules were not being called. I assumed this was working as 
designed, and started only using validate so my async rules would run.

The issue I described happens with a set of async rules I have (that can 
go off and make calls to a database).

Thanks,

Glenn

**Comment by jmdobry** [comment]
Yeah, the `Sync` in `validateSync` stands for "synchronous`. It's faster, and the implementation for it is muuuuch simpler, but it doesn't support asynchronous rules. You have to use `validate` in order to use asynchronous rules. The implementation for `validate` is much more complex (you've probably seen) because of the need to queue a bunch of different async tasks, and I believe your fix will probably work.

**Comment by gtarcea** [comment]
I did see that :-) 
After I thought about it, it made a lot of sense that validateSync skipped the async rules. Perhaps that could be added to the documentation?

The fix is working for me so far. If I run into other issues with it I'll fix them and submit another pull request.

**Comment by jmdobry** [comment]
@gtarcea Thanks for the PR!
